############# model parameters #############
AGENT:
    env_params:
        env_name: 'blocks_simple'
        action_dim: 32          # 2 sat, 1 obj, 7 operators
        state_dim: 170           # 18*5 + 4*20 = 170
        obj_centric_feat_dim: 18
        rel_feat_dim: 4
        num_blocks: 4
    log_dir: ./log/test
    model_path: './model'
    model_id: 1
    grader_model: "mlp" # only supports mlp
    planner:
        epsilon: 0.4
        max_buffer_size: 100000
        pretrain_buffer_size: 1
        validation_flag: True
        validation_freq: 1      # the frequency of validation
        validation_ratio: 0.2   # ratio of validation set
        lr: 0.001
        n_epochs: 300        
        hidden_dim: 4           # hidden layer number
        hidden_size: 125         # hidden layer size
        batch_size: 512
        scale: 1                # normalizing scale for NN input and output, determined by envs
        horizon: 5             # max step for each episode
        popsize: 80            # how many random samples for mpc
        mpc:
            type: 'Random'
            horizon: 15          # should be consistent with the max step
            popsize: 200        # how many random samples for mpc
            gamma: 1            # reward discount coefficient
            max_iters: 5
            num_elites: 10
    discover:
        discovery_interval: 10